const { createGlobPatternsForDependencies } = require('@nx/angular/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  darkMode: ['class', '[data-mode="dark"]'],
  theme: {
    extend: {
      colors: {
        'mui-white': {
          DEFAULT: 'var(--mui-color-white)',
        },
        'mui-black': {
          DEFAULT: 'var(--mui-color-black)',
        },
        'mui-primary': {
          50: 'var(--mui-color-primary-50)',
          100: 'var(--mui-color-primary-100)',
          200: 'var(--mui-color-primary-200)',
          300: 'var(--mui-color-primary-300)',
          400: 'var(--mui-color-primary-400)',
          500: 'var(--mui-color-primary-500)',
          600: 'var(--mui-color-primary-600)',
          700: 'var(--mui-color-primary-700)',
          800: 'var(--mui-color-primary-800)',
          900: 'var(--mui-color-primary-900)',
          950: 'var(--mui-color-primary-950)',
        },
        'mui-secondary': {
          50: 'var(--mui-color-secondary-50)',
          100: 'var(--mui-color-secondary-100)',
          200: 'var(--mui-color-secondary-200)',
          300: 'var(--mui-color-secondary-300)',
          400: 'var(--mui-color-secondary-400)',
          500: 'var(--mui-color-secondary-500)',
          600: 'var(--mui-color-secondary-600)',
          700: 'var(--mui-color-secondary-700)',
          800: 'var(--mui-color-secondary-800)',
          900: 'var(--mui-color-secondary-900)',
          950: 'var(--mui-color-secondary-950)',
        },
        'mui-success': {
          50: 'var(--mui-color-success-50)',
          100: 'var(--mui-color-success-100)',
          200: 'var(--mui-color-success-200)',
          300: 'var(--mui-color-success-300)',
          400: 'var(--mui-color-success-400)',
          500: 'var(--mui-color-success-500)',
          600: 'var(--mui-color-success-600)',
          700: 'var(--mui-color-success-700)',
          800: 'var(--mui-color-success-800)',
          900: 'var(--mui-color-success-900)',
          950: 'var(--mui-color-success-950)',
        },
        'mui-danger': {
          50: 'var(--mui-color-danger-50)',
          100: 'var(--mui-color-danger-100)',
          200: 'var(--mui-color-danger-200)',
          300: 'var(--mui-color-danger-300)',
          400: 'var(--mui-color-danger-400)',
          500: 'var(--mui-color-danger-500)',
          600: 'var(--mui-color-danger-600)',
          700: 'var(--mui-color-danger-700)',
          800: 'var(--mui-color-danger-800)',
          900: 'var(--mui-color-danger-900)',
          950: 'var(--mui-color-danger-950)',
        },
        'mui-warning': {
          50: 'var(--mui-color-warning-50)',
          100: 'var(--mui-color-warning-100)',
          200: 'var(--mui-color-warning-200)',
          300: 'var(--mui-color-warning-300)',
          400: 'var(--mui-color-warning-400)',
          500: 'var(--mui-color-warning-500)',
          600: 'var(--mui-color-warning-600)',
          700: 'var(--mui-color-warning-700)',
          800: 'var(--mui-color-warning-800)',
          900: 'var(--mui-color-warning-900)',
          950: 'var(--mui-color-warning-950)',
        },
        'mui-info': {
          50: 'var(--mui-color-info-50)',
          100: 'var(--mui-color-info-100)',
          200: 'var(--mui-color-info-200)',
          300: 'var(--mui-color-info-300)',
          400: 'var(--mui-color-info-400)',
          500: 'var(--mui-color-info-500)',
          600: 'var(--mui-color-info-600)',
          700: 'var(--mui-color-info-700)',
          800: 'var(--mui-color-info-800)',
          900: 'var(--mui-color-info-900)',
          950: 'var(--mui-color-info-950)',
        },
      },
      backgroundColor: {
        'mui-primary': {
          50: 'var(--mui-bg-color-primary-50)',
          100: 'var(--mui-bg-color-primary-100)',
          200: 'var(--mui-bg-color-primary-200)',
          300: 'var(--mui-bg-color-primary-300)',
          400: 'var(--mui-bg-color-primary-400)',
          500: 'var(--mui-bg-color-primary-500)',
          600: 'var(--mui-bg-color-primary-600)',
          700: 'var(--mui-bg-color-primary-700)',
          800: 'var(--mui-bg-color-primary-800)',
          900: 'var(--mui-bg-color-primary-900)',
          950: 'var(--mui-bg-color-primary-950)',
        },
        'mui-secondary': {
          50: 'var(--mui-bg-color-secondary-50)',
          100: 'var(--mui-bg-color-secondary-100)',
          200: 'var(--mui-bg-color-secondary-200)',
          300: 'var(--mui-bg-color-secondary-300)',
          400: 'var(--mui-bg-color-secondary-400)',
          500: 'var(--mui-bg-color-secondary-500)',
          600: 'var(--mui-bg-color-secondary-600)',
          700: 'var(--mui-bg-color-secondary-700)',
          800: 'var(--mui-bg-color-secondary-800)',
          900: 'var(--mui-bg-color-secondary-900)',
          950: 'var(--mui-bg-color-secondary-950)',
        },
        'mui-success': {
          50: 'var(--mui-bg-color-success-50)',
          100: 'var(--mui-bg-color-success-100)',
          200: 'var(--mui-bg-color-success-200)',
          300: 'var(--mui-bg-color-success-300)',
          400: 'var(--mui-bg-color-success-400)',
          500: 'var(--mui-bg-color-success-500)',
          600: 'var(--mui-bg-color-success-600)',
          700: 'var(--mui-bg-color-success-700)',
          800: 'var(--mui-bg-color-success-800)',
          900: 'var(--mui-bg-color-success-900)',
          950: 'var(--mui-bg-color-success-950)',
        },
        'mui-danger': {
          50: 'var(--mui-bg-color-danger-50)',
          100: 'var(--mui-bg-color-danger-100)',
          200: 'var(--mui-bg-color-danger-200)',
          300: 'var(--mui-bg-color-danger-300)',
          400: 'var(--mui-bg-color-danger-400)',
          500: 'var(--mui-bg-color-danger-500)',
          600: 'var(--mui-bg-color-danger-600)',
          700: 'var(--mui-bg-color-danger-700)',
          800: 'var(--mui-bg-color-danger-800)',
          900: 'var(--mui-bg-color-danger-900)',
          950: 'var(--mui-bg-color-danger-950)',
        },
        'mui-warning': {
          50: 'var(--mui-bg-color-warning-50)',
          100: 'var(--mui-bg-color-warning-100)',
          200: 'var(--mui-bg-color-warning-200)',
          300: 'var(--mui-bg-color-warning-300)',
          400: 'var(--mui-bg-color-warning-400)',
          500: 'var(--mui-bg-color-warning-500)',
          600: 'var(--mui-bg-color-warning-600)',
          700: 'var(--mui-bg-color-warning-700)',
          800: 'var(--mui-bg-color-warning-800)',
          900: 'var(--mui-bg-color-warning-900)',
          950: 'var(--mui-bg-color-warning-950)',
        },
        'mui-info': {
          50: 'var(--mui-bg-color-info-50)',
          100: 'var(--mui-bg-color-info-100)',
          200: 'var(--mui-bg-color-info-200)',
          300: 'var(--mui-bg-color-info-300)',
          400: 'var(--mui-bg-color-info-400)',
          500: 'var(--mui-bg-color-info-500)',
          600: 'var(--mui-bg-color-info-600)',
          700: 'var(--mui-bg-color-info-700)',
          800: 'var(--mui-bg-color-info-800)',
          900: 'var(--mui-bg-color-info-900)',
          950: 'var(--mui-bg-color-info-950)',
        },
      },
      spacing: {
        '0.5': 'var(--mui-spacing-0\\.5)',
        '1': 'var(--mui-spacing-1)',
        '1.5': 'var(--mui-spacing-1\\.5)',
        '2': 'var(--mui-spacing-2)',
        '2.5': 'var(--mui-spacing-2\\.5)',
        '3': 'var(--mui-spacing-3)',
        '3.5': 'var(--mui-spacing-3\\.5)',
        '4': 'var(--mui-spacing-4)',
        '5': 'var(--mui-spacing-5)',
        '6': 'var(--mui-spacing-6)',
        '7': 'var(--mui-spacing-7)',
        '8': 'var(--mui-spacing-8)',
        '9': 'var(--mui-spacing-9)',
        '10': 'var(--mui-spacing-10)',
        '11': 'var(--mui-spacing-11)',
        '12': 'var(--mui-spacing-12)',
        '13': 'var(--mui-spacing-13)',
        '14': 'var(--mui-spacing-14)',
        '16': 'var(--mui-spacing-16)',
        '20': 'var(--mui-spacing-20)',
        '24': 'var(--mui-spacing-24)',
        '28': 'var(--mui-spacing-28)',
        '32': 'var(--mui-spacing-32)',
        '36': 'var(--mui-spacing-36)',
        '40': 'var(--mui-spacing-40)',
        '44': 'var(--mui-spacing-44)',
        '48': 'var(--mui-spacing-48)',
        '52': 'var(--mui-spacing-52)',
        '56': 'var(--mui-spacing-56)',
        '60': 'var(--mui-spacing-60)',
        '64': 'var(--mui-spacing-64)',
        '72': 'var(--mui-spacing-72)',
        '80': 'var(--mui-spacing-80)',
        '96': 'var(--mui-spacing-96)',
      },
      borderRadius: {
        DEFAULT: 'var(--mui-border-radius)',
        'xs': 'var(--mui-border-radius-xs)',
        'sm': 'var(--mui-border-radius-sm)',
        'md': 'var(--mui-border-radius-md)',
        'lg': 'var(--mui-border-radius-lg)',
        'xl': 'var(--mui-border-radius-xl)',
        '2xl': 'var(--mui-border-radius-2xl)',
        '3xl': 'var(--mui-border-radius-3xl)',
      },
      borderWidth: {
        DEFAULT: 'var(--mui-border-width)',
        '0': 'var(--mui-border-width-0)',
        '2': 'var(--mui-border-width-2)',
        '4': 'var(--mui-border-width-4)',
        '8': 'var(--mui-border-width-8)',
      },
      borderColor: {
        'mui-primary': {
          50: 'var(--mui-border-color-primary-50)',
          100: 'var(--mui-border-color-primary-100)',
          200: 'var(--mui-border-color-primary-200)',
          300: 'var(--mui-border-color-primary-300)',
          400: 'var(--mui-border-color-primary-400)',
          500: 'var(--mui-border-color-primary-500)',
          600: 'var(--mui-border-color-primary-600)',
          700: 'var(--mui-border-color-primary-700)',
          800: 'var(--mui-border-color-primary-800)',
          900: 'var(--mui-border-color-primary-900)',
          950: 'var(--mui-border-color-primary-950)',
        },
        'mui-secondary': {
          50: 'var(--mui-border-color-secondary-50)',
          100: 'var(--mui-border-color-secondary-100)',
          200: 'var(--mui-border-color-secondary-200)',
          300: 'var(--mui-border-color-secondary-300)',
          400: 'var(--mui-border-color-secondary-400)',
          500: 'var(--mui-border-color-secondary-500)',
          600: 'var(--mui-border-color-secondary-600)',
          700: 'var(--mui-border-color-secondary-700)',
          800: 'var(--mui-border-color-secondary-800)',
          900: 'var(--mui-border-color-secondary-900)',
          950: 'var(--mui-border-color-secondary-950)',
        },
        'mui-success': {
          50: 'var(--mui-border-color-success-50)',
          100: 'var(--mui-border-color-success-100)',
          200: 'var(--mui-border-color-success-200)',
          300: 'var(--mui-border-color-success-300)',
          400: 'var(--mui-border-color-success-400)',
          500: 'var(--mui-border-color-success-500)',
          600: 'var(--mui-border-color-success-600)',
          700: 'var(--mui-border-color-success-700)',
          800: 'var(--mui-border-color-success-800)',
          900: 'var(--mui-border-color-success-900)',
          950: 'var(--mui-border-color-success-950)',
        },
        'mui-danger': {
          50: 'var(--mui-border-color-danger-50)',
          100: 'var(--mui-border-color-danger-100)',
          200: 'var(--mui-border-color-danger-200)',
          300: 'var(--mui-border-color-danger-300)',
          400: 'var(--mui-border-color-danger-400)',
          500: 'var(--mui-border-color-danger-500)',
          600: 'var(--mui-border-color-danger-600)',
          700: 'var(--mui-border-color-danger-700)',
          800: 'var(--mui-border-color-danger-800)',
          900: 'var(--mui-border-color-danger-900)',
          950: 'var(--mui-border-color-danger-950)',
        },
        'mui-warning': {
          50: 'var(--mui-border-color-warning-50)',
          100: 'var(--mui-border-color-warning-100)',
          200: 'var(--mui-border-color-warning-200)',
          300: 'var(--mui-border-color-warning-300)',
          400: 'var(--mui-border-color-warning-400)',
          500: 'var(--mui-border-color-warning-500)',
          600: 'var(--mui-border-color-warning-600)',
          700: 'var(--mui-border-color-warning-700)',
          800: 'var(--mui-border-color-warning-800)',
          900: 'var(--mui-border-color-warning-900)',
          950: 'var(--mui-border-color-warning-950)',
        },
        'mui-info': {
          50: 'var(--mui-border-color-info-50)',
          100: 'var(--mui-border-color-info-100)',
          200: 'var(--mui-border-color-info-200)',
          300: 'var(--mui-border-color-info-300)',
          400: 'var(--mui-border-color-info-400)',
          500: 'var(--mui-border-color-info-500)',
          600: 'var(--mui-border-color-info-600)',
          700: 'var(--mui-border-color-info-700)',
          800: 'var(--mui-border-color-info-800)',
          900: 'var(--mui-border-color-info-900)',
          950: 'var(--mui-border-color-info-950)',
        },
      }
    },
  },
  plugins: [
    require('tailwindcss-animation-delay'),
  ],
};
